CREATE TABLE DUENO(
    ID_DUENO INT AUTO_INCREMENT,
    NOMBRE VARCHAR(20),
    APELLIDO VARCHAR(20),
    TELEFONO VARCHAR(9),
    CONSTRAINT PK_DUENO PRIMARY KEY (ID_DUENO)
);

CREATE TABLE PERRO(
    ID_PERRO INT AUTO_INCREMENT,
    NOMBRE VARCHAR(20),
    RAZA VARCHAR(20),
    EDAD INT,
    PESO INT,
    ID_DUENO INT,
    CONSTRAINT PK_PERRO PRIMARY KEY (ID_PERRO),
    CONSTRAINT FK_PERRO_DUENO FOREIGN KEY (ID_DUENO) REFERENCES DUENO(ID_DUENO)
);

CREATE TABLE SERVICIO(
    ID_SERVICIO INT,
    NOMBRE VARCHAR(20),
    PRECIO INT,
    DESCRIPCION VARCHAR(100),
    CONSTRAINT PK_SERVICIO PRIMARY KEY (ID_SERVICIO)
);

CREATE TABLE CITA(
    ID_CITA INT AUTO_INCREMENT,
    FECHA DATE,
    ESTADO VARCHAR(20),
    ID_PERRO INT,
    ID_SERVICIO INT,
    CONSTRAINT PK_CITA PRIMARY KEY (ID_CITA),
    CONSTRAINT FK_CITA_PERRO FOREIGN KEY (ID_PERRO) REFERENCES PERRO(ID_PERRO),
    CONSTRAINT FK_CITA_SERVICIO FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO(ID_SERVICIO)
);

CREATE TABLE HISTORIAL_DE_SALUD(
    ID_HISTORIAL INT AUTO_INCREMENT,
    FECHA DATE,
    DESCRIPCION VARCHAR(150),
    ID_PERRO INT,
    CONSTRAINT PK_HISTORIAL_DE_SALUD PRIMARY KEY (ID_HISTORIAL),
    CONSTRAINT FK_HISTORIAL_PERRO FOREIGN KEY (ID_PERRO) REFERENCES PERRO(ID_PERRO)
);

